### PR TITLE
update project title #6

### PR DESCRIPTION
**Pull request by korbinib**
This is a merge of 2 projects and the updated title corresponds with the title in easychair.

### CODE REVIEW

**Comment by korbinib** [comment]
@martin-nc would you please consider the proposed change?

**Comment by martin-nc** [comment]
@korbinib Yes, Jen says this is okay. Can you also change it on EasyChair?

**Comment by korbinib** [comment]
@martin-nc Great, thanks. - I wanted to change this as this is already the title on easychair:
image

**Comment by martin-nc** [comment]
Ah, sorry - we didn't check. All fine now.

**Pull request merged**
